const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "./images/p6.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "It is beatifull product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "./images/p3.jpg",
      price: 120,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "It is beatifull product",
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "It is beatifull product",
    },
    {
      _id: "3",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "./images/p2.jpg",
      price: 100,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 10,
      description: "It is beatifull product",
    },
    {
      _id: "4",
      name: "Reebook Slim Shirt",
      category: "Shirts",
      image: "./images/p3.jpg",
      price: 120,
      brand: "Reebook",
      rating: 4.5,
      numReviews: 10,
      description: "It is beatifull product",
    },
    {
      _id: "5",
      name: "Brand Slim Shirt",
      category: "Shirts",
      image: "./images/p4.jpg",
      price: 120,
      brand: "Brand",
      rating: 4.5,
      numReviews: 10,
      description: "It is beatifull product",
    },
    {
      _id: "6",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "./images/p5.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "It is beatifull product",
    },
    {
      _id: "7",
      name: "Polo Slim Shirt",
      category: "Pants",
      image: "./images/p6.jpg",
      price: 150,
      brand: "Polo",
      rating: 4.5,
      numReviews: 13,
      description: "It is beatifull product",
    },
  ],
};
export default data;
